Rk1
java-park-mail-ru/Accord-02-2018 pull request #1
Opened 2018-02-28 13:53 UTC by Meganster

2018-02-28 18:18 UTC, KSolovyev requested changes

2018-02-28 18:18 UTC, KSolovyev commented on pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
есть в spring boot starter web

2018-02-28 18:18 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +@CrossOrigin({"*"})
на generic домен не высылается кука

2018-02-28 18:18 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +    private UserDAO userService;
давайте инжектить сервисы через конструктор

2018-02-28 18:18 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +        final JSONObject responseJson = new JSONObject();
Нужно сделать, чтобы все json-сущности имели модели

2018-02-28 18:18 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +                         HttpServletResponse response) throws JSONException {
HttpServletResponse не надо использовать. Вместо него нужно возвращать ResponseEntity

2018-02-28 18:18 UTC, KSolovyev commented on src/main/java/services/dao/UserDAO.java
> +            return false;
Если падает база должна быть 500 ошибка

2018-02-28 18:18 UTC, KSolovyev commented on src/main/java/services/dao/UserDAO.java
> +        if (condition) {
а если нет?

2018-02-28 18:18 UTC, KSolovyev commented on pom.xml
> +            <artifactId>swagger-jaxrs</artifactId>
не используется

2018-02-28 18:18 UTC, KSolovyev commented on pom.xml
> +            <groupId>com.cedarsoft.serialization</groupId>
не используется

2018-02-28 18:18 UTC, KSolovyev commented on src/main/resources/db/migration/V1__init.sql
> +CREATE TABLE "User" (
Индексы?

2018-02-28 18:18 UTC, KSolovyev commented on src/main/resources/application.properties
> +spring.datasource.url=${JDBC_DATABASE_URL}
Раз добавили базу, то нужно добавить тест на поднятие контекста спринга

2018-02-28 18:18 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +            // значит такой юзер с таким мейлом уже существует
или у нас база отвалилась

2018-02-28 18:18 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +            response.setStatus(HttpServletResponse.SC_FORBIDDEN);
Если произошел конфликт, то логично вернуть 409 Conflict

2018-02-28 18:18 UTC, KSolovyev commented on pom.xml
> +        <java.version>1.8</java.version>
java 9

2018-02-28 19:06 UTC, Meganster commented on pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
Исправлено

2018-02-28 19:07 UTC, Meganster commented on src/main/java/services/dao/UserDAO.java
> +        if (condition) {
метод является void, поэтому ничего не произойдет, ошибки не возникнет

2018-02-28 19:08 UTC, Meganster commented on pom.xml
> +        <java.version>1.8</java.version>
Проблема, специально поставил версию 1.8, т.к. при 1.9 не собирается травис. Гугл проблему не помог решить, разве что указал на возможную смену на 1.8

2018-02-28 19:08 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +            response.setStatus(HttpServletResponse.SC_FORBIDDEN);
Исправлено

2018-02-28 19:08 UTC, Meganster commented on pom.xml
> +            <groupId>com.cedarsoft.serialization</groupId>
Исправлено

2018-02-28 19:08 UTC, Meganster commented on pom.xml
> +            <artifactId>swagger-jaxrs</artifactId>
Исправлено

2018-02-28 20:31 UTC, Meganster commented on src/main/resources/db/migration/V1__init.sql
> +CREATE TABLE "User" (
БД прикрутил, чтобы только попробовать, индексы еще не продумывал

2018-02-28 22:40 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +                         HttpServletResponse response) throws JSONException {
Исправлено

2018-02-28 22:40 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +        final JSONObject responseJson = new JSONObject();
Исправлено

2018-02-28 22:44 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +@CrossOrigin({"*"})
Исправлено

2018-02-28 22:54 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +@CrossOrigin({"*"})
Исправил, но после этого перестали отправляться запросы с фронт-сервера, откатил

2018-03-01 13:50 UTC, KSolovyev commented on pom.xml
> +        <java.version>1.8</java.version>
я показывал пример на java 9, который travis собирает

2018-03-01 20:37 UTC, Meganster commented on pom.xml
> +        <java.version>1.8</java.version>
Исправил

2018-03-24 10:14 UTC, KSolovyev requested changes

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +    private final UserDAO userService = new UserDAO();
а зачем здесь такой странный дефолт. UserDAO - это ведь спринговый сервис и он должен только через спринговый контекст создаваться
И давайте зависимость все таки в конструктор перенесем

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +                    "Unsuccessful registration"));
User with same email already exists

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +        if (userService.register(user)) {
блок надо переписать
проверяем `if(!userService.register(user)){...}` 
тогда блок else можно будет совсем убрать

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +        if (userFromSession != null) {
здесь тоже надо сделать `userFromSession == null`
и коммент убрать

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/controller/UserController.java
> +        if (userService.updateUser(userForUpdate)) {
здесь тоже надо перевернуть условия и убрать коммент.
В общем везде в коде так надо сделать

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/dao/UserDAO.java
> +        } catch (DataAccessException e) {
исключения базы данных надо логировать

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/dao/UserDAO.java
> +            return false;
вот здесь правду написал. Должна быть 500 ошибка, если падает база. DataAccessException - не всегда про совпадающие ключи

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/dao/UserDAO.java
> +            return null;
если сломалась база, здесь тоже должна быть 500 ошибка

2018-03-24 10:14 UTC, KSolovyev commented on src/main/java/services/dao/UserDAO.java
> +                return false;
вот здесь тоже должна быть ошибка, если база сломалась

2018-03-29 14:04 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +        if (userService.updateUser(userForUpdate)) {
Исправил

2018-03-29 14:04 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +        if (userFromSession != null) {
Исправил

2018-03-29 14:04 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +        if (userService.register(user)) {
Исправил

2018-03-29 14:05 UTC, Meganster commented on src/main/java/services/controller/UserController.java
> +                    "Unsuccessful registration"));
Исправил

2018-03-29 14:43 UTC, Meganster commented on src/main/java/services/dao/UserDAO.java
> +            return null;
Исправлено

2018-03-29 14:43 UTC, Meganster commented on src/main/java/services/dao/UserDAO.java
> +                return false;
Исправлено

2018-03-29 14:57 UTC, Meganster commented on src/main/java/services/dao/UserDAO.java
> +        } catch (DataAccessException e) {
Добавил логирование

2018-04-04 20:41 UTC, Meganster commented
Константин, примите, пожалуйста, пр

2018-04-04 21:01 UTC, merged