Rk2
java-park-mail-ru/Accord-02-2018 pull request #3
Opened 2018-04-05 08:30 UTC by Meganster

2018-04-08 17:15 UTC, Badya requested changes
Почему junit4, на лекции был 5

2018-04-08 17:15 UTC, Badya commented on src/test/java/services/dao/UserDAOTest.java
> +        if (userService.register(user)) {
assertTrue

2018-04-08 17:15 UTC, Badya commented on src/test/java/services/dao/UserDAOTest.java
> +        if (userService.register(user)) {
assertTrue

2018-04-08 17:15 UTC, Badya commented on src/test/java/services/dao/UserDAOTest.java
> +        if (userService.register(user)) {
assertTrue

2018-04-08 17:15 UTC, Badya commented on src/test/java/services/dao/UserDAOTest.java
> +        final User userToRegister = new User(NICKNAME, LOGIN, PASSWORD, 0);
User можно инициализовать в `@Before` и тогда не нужно статических строк и прочего

2018-04-08 17:15 UTC, Badya commented on src/test/java/services/controller/UserControllerSessionsTest.java
> +    private List<String> login() {
private методы лучше писать после public

2018-04-08 17:15 UTC, Badya commented on src/main/java/services/dao/UserDAO.java
> +    private final Logger logger = LoggerFactory.getLogger(UserDAO.class.getName());
static

2018-04-16 12:01 UTC, Meganster commented on src/main/java/services/dao/UserDAO.java
> +    private final Logger logger = LoggerFactory.getLogger(UserDAO.class.getName());
Исправил

2018-04-16 12:01 UTC, Meganster commented on src/test/java/services/dao/UserDAOTest.java
> +        final User userToRegister = new User(NICKNAME, LOGIN, PASSWORD, 0);
Исправил

2018-04-16 12:01 UTC, Meganster commented on src/test/java/services/dao/UserDAOTest.java
> +        if (userService.register(user)) {
Исправил

2018-04-16 12:01 UTC, Meganster commented on src/test/java/services/dao/UserDAOTest.java
> +        if (userService.register(user)) {
Исправил

2018-04-16 12:01 UTC, Meganster commented on src/test/java/services/dao/UserDAOTest.java
> +        if (userService.register(user)) {
Исправил

2018-05-03 11:38 UTC, merged