Rk3
java-park-mail-ru/Accord-02-2018 pull request #4
Opened 2018-05-02 21:59 UTC by Meganster

2018-05-03 08:52 UTC, isopov commented
- `spring.datasource.username = postgres` - это больно бьёт в неожиданный момент
- `spring.datasource.driver-class-name=org.postgresql.Driver` - а зачем это нужно?
- бут версии 2.0.1 вышел еще до РК2))
- Junit просили 5 - настаиваете делать на 4-ом?
- тестов на механику напишете?
- spring-websocket  - почему зависимость на него, а не на стартер?
- spring-websocket & spring-security-core - почему их версии явно указываете свои, а не пользуетесь управляемыми из бута?
- ru.mail.park.websocket.mechanics.TaskRunner#INSTANCE - синглтоны по-хорошему должны все управляться спрингом...
- `catch (RuntimeException e) { LOGGER.warn("GameMechanics failed"); }` - очень плохой паттерн логирования ошибок. Хороший отлчиается совсем чуть - `catch (RuntimeException e) { LOGGER.warn("GameMechanics failed", e); }`
- Засилие JSONObject обескураживает - чем вам Jackson & ObjectMapper не угодил?
- ru.mail.park.websocket.services.GameRoomService#queue - LinkedList - это потоко-небезопасная коллекция. Очевидно тут надо на LinkedBlockingDeque заменить, но для безопасной многопоточности этого может и не хватить...
- ru.mail.park.websocket.mechanics.GameRoom#isFinished - где-то используется?
- ru.mail.park.websocket.mechanics.GameRoom#userService - тоже нигде не используется и в таком месте и не должен - их игрового цикла реального времени не стоит синхронно ходить в базу.
- ru.mail.park.websocket.mechanics.GameLoop#stop - в единственном месте использования сразу после вызова этого метода происходит `thread.interrupt()` на том же потоке? Зачем интерраптить по два раза по два раза?
- `catch (InterruptedException e) { LOGGER.warn("interupted"); }` - если завершение через interrupt это нормальное завершение, почему логирование с warn?

2018-05-03 08:53 UTC, isopov requested changes
Замечания в общем комментарии к PR

2018-05-03 08:59 UTC, isopov commented
О! И шифрования паролей то нет... https://park.mail.ru/blog/topic/view/7197/ - сделайте, пожалуйста.

2018-05-03 15:28 UTC, Meganster commented
spring.datasource.username = postgres - это больно бьёт в неожиданный момент - исправил
spring.datasource.driver-class-name=org.postgresql.Driver - а зачем это нужно? - исправил
бут версии 2.0.1 вышел еще до РК2)) - исправил
spring-websocket & spring-security-core - почему их версии явно указываете свои, а не пользуетесь управляемыми из бута? - Исправил
catch (RuntimeException e) { LOGGER.warn("GameMechanics failed"); } - очень плохой паттерн логирования ошибок. Хороший отлчиается совсем чуть - catch (RuntimeException e) { LOGGER.warn("GameMechanics failed", e); } - Исправил
ru.mail.park.websocket.services.GameRoomService#queue - LinkedList - это потоко-небезопасная коллекция. Очевидно тут надо на LinkedBlockingDeque заменить, но для безопасной многопоточности этого может и не хватить... - исправил
ru.mail.park.websocket.mechanics.GameRoom#isFinished - где-то используется? - Убрал
ru.mail.park.websocket.mechanics.GameRoom#userService - тоже нигде не используется и в таком месте и не должен - их игрового цикла реального времени не стоит синхронно ходить в базу. - Убрал
ru.mail.park.websocket.mechanics.GameLoop#stop - в единственном месте использования сразу после вызова этого метода происходит thread.interrupt() на том же потоке? Зачем интерраптить по два раза? - Исправил
catch (InterruptedException e) { LOGGER.warn("interupted"); } - если завершение через interrupt это нормальное завершение, почему логирование с warn? -Исправил

2018-05-04 06:55 UTC, isopov commented
https://github.com/Meganster/Accord-02-2018/pull/1 - что-то быстрее показать, чем просить сделать.

тестов на игровую механику совсем не хотите писать?

2018-05-23 16:11 UTC, merged

2018-05-23 16:12 UTC, isopov commented
Ну не хотите, как хотите))